version: '3'

services:

  mongo:
      image: mongo
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSW}
      volumes:
      - .volumes/MongoDB:/data/db